configs: configs/datasets/vci_closeup_01/vci_closeup_01.yaml

dataloader_cfg: # we see the term "dataloader" as one word?
    dataset_cfg: &dataset_cfg
        data_root: data/vci_closeup_01/sample_0000
        images_dir: images

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
