dataloader_cfg: # we see the term "dataloader" as one word?
    dataset_cfg: &dataset_cfg
        masks_dir: masks # {data_root}/{masks_dir,images_dir}/{camera_name}/000000{.jpg,.png}
        #view_sample: [0, 1, 1] # start, end, step. 0 means the first view, null means the last view
        frame_sample: [0, 1, 1] # start, end, step. 0 means the first frame, null means the last frame

model_cfg:
    sampler_cfg:
        bg_brightness: 0.0
    renderer_cfg:
        bg_brightness: 0.0

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
        frame_sample: [0, 1, 1] # make rendering faster, controls which of the views and frames to load
#    sampler_cfg:
     #view_sample: [0, 1, 1] # make rendering faster, if doing IBR, change the view_sample in sampler_cfg to control which view to render

viewer_cfg:
    use_window_focal: True # when initializing viewer, use window H and W to calculate focal to give a better experience
    # init_camera_index: 10
    camera_cfg:
        world_up: [-1.0, 0.0, 0.0]
        origin: [0.0, 0.05, 2.5]
        R: [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
        T: [[0.0], [0.0], [0.0]]
