name: 4k4d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - iopath::iopath
  - bottler::nvidiacub
  - pytorch3d::pytorch3d
  - numpy<2
  - open3d
  - pip
  - pip:
    - -r requirements.txt
# How to Use:
# 1. conda env create --file environment.yml
# 2. wait for everything to install, this may take VERY long
# 3. conda activate 4k4d
# 4. pip install -e . --no-build-isolation --no-deps 
